name: Jose Haynes
favicon: null
layout_spectrum: 0.5460098166950047
typography_spectrum: 0.19193926267325878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.19866147311404347
  lightness: 0.06126208766363561
  saturation: 0.2543454880360514
  rhythmicContrast: 0.4530574707314372
purpose: []
